### ISSUE TITLE
Are there scripts how to train the model of 8 Million PBMC Atlas?

### ISSUE THREAD

**Issue by zacharylau10** [theislab/scPoli_reproduce#10]
Hi, 
Thanks for your great jobs.
I'm really interested with 8 Million PBMC data, and it's the biggest scRNA-seq collection I‘ve ever seen.
Could you provide the scripts of processing and train the PBMC data? I really want to learn how to handle million-level scRNA-seq Data.

Thanks!!

**Comment by cdedonno** [comment]
Hi @zacharylau10, thanks for the interest. I have added a folder called pbmc8M which includes two notebooks for data prepping and one for training. 

In general, the biggest hurdle is having hardware capable of handling such large datasets, the preprocessing and training steps are otherwise more or less identical to what you would do on a smaller dataset.

**Comment by zacharylau10** [comment]
Thanks for the quick response!!! @cdedonno
