### ISSUE TITLE
PBMC reproducibility code

### ISSUE THREAD

**Issue by Nusob888** [theislab/scPoli_reproduce#14]
Hi, 

Amazing work. I am trying to understand how the PBMC dataset was generated, but I think you may be missing a few intermediate scripts?

In the notebooks you supply, you appear to create a reference and query dataset, and only train on the reference dataset?
Although this is unclear, as you read in the pbmc_raw.h5ad, but the code leading up to its generation is not trackable as you only ever write the following h5ad objects: 
`ref_adata.write('data/czi_8M_PBMC_lataq_ref_10k_loSuHanifa.h5ad')
query_adata.write('data/czi_8M_PBMC_lataq_querySu_10k_loSuHanifa.h5ad')`

From the code available I think the following was done:
1) A reference dataset was created by subsetting out: ['10_1126_sciimmunol_abd1554','10_1038_s41591_021_01329_2']
1a) A query dataset is then created using these two datasets
1b) For unclear reasons (not annotated), you removed these two datasets ['villani_pbmc','vento_tormo_pbmc']

2) HVGs were then calculated using only the reference datasets and not the query. 

3) You then create a model using pbmc_raw.h5ad, which based on the figure reproducibility code must be the whole dataset? as it contains the query datasets. 
3a) If this is the case, why were hvgs only calculated on the reference dataset that excluded ['10_1126_sciimmunol_abd1554','10_1038_s41591_021_01329_2']? I can't quite figure out why there would be a need to calculate hvgs without these datasets, if the final model is trained on the whole dataset. 

Sorry for going to this detail, since I am keen to use scPoli, I wanted to understand these choices as they don't follow the conventional norm with the code at hand. Unless, there is other code missing. 

Many thanks in advance

**Comment by cdedonno** [comment]
Hi @Nusob888, this repo is admittedly not as clean as I'd like it to be. The problem is that there is a bit of a mix up of different versions of the code and inconsistent naming plus notebook versions. 

I unfortunately do not have access anymore to the scripts used since I have left the lab a few months ago. At the beginning we were performing reference mapping with this dataset, which was scrapped in the final version of the paper. Also the datasets that you see excluded there ('villani_pbmc', 'vento_torno_pbmc') were unpublished data, hence why we removed them.

I can tell you that the procedure for HVG did not look any different for this dataset. Especially since we eventually chose not to split in reference and query, we computed them over all studies. Sorry for the confusion this has created, let me know if you have further questions.
